### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by kirkhauck** [activecm/threat-tools#14]
The current README needs editing for clearer step-by-step instructions to improve readability and usability for the average user. The edits should prompt the user towards a set of scripts that should work for most cases, describe which device needs to run which script pair, have clear instructions and descriptions for each script, and show the dependencies for each script.

Additionally, the help messages for the scripts do not have a consistent pattern. The help messages should be edited for consistency, and the README should tell the user how to access the help message for each script.

**Comment by Zalgo2462** [comment]
Closed by #15
